services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "6666:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - my_network
    platform: linux/amd64
    mem_limit: 2g
    memswap_limit: 4g

networks:
  my_network:
    name: my_network
    driver: bridge
