services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "9999:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - my_network
    platform: linux/amd64
    mem_limit: 2g
    memswap_limit: 4g
    env_file:
      - ./apps/web/.env
  cron:
    build:
      context: .
      dockerfile: ./apps/cron/Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    env_file:
      - ./apps/cron/.env

networks:
  my_network:
    name: my_network
    driver: bridge
