services:
  line-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/youmingyeh/lio-line:latest
    ports:
      - "8888:8888"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
